vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.background = 'dark'
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = false
vim.opt.shiftwidth = 2
vim.opt.autoindent = true
vim.opt.ch = 0
vim.opt.clipboard = 'unnamedplus'
vim.opt.scrolloff = 10
vim.opt.updatetime = 250
vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
vim.o.winborder = 'rounded'
